version: "3.7"
services:
  octave:
    image: docker.io/gnuoctave/octave:6.3.0
    environment:
      DISPLAY: ${HOSTNAME}:0
      XDG_RUNTIME_DIR: /home/${NB_USER}/xdg_runtime_dir
      NB_USER: ${NB_USER}
      NB_GID: ${NB_GID}
      GRANT_SUDO: 'yes'
      LIBGL_ALWAYS_INDIRECT: 1
    command: start.sh octave --gui
    user: root
    network_mode: host
    volumes:
      - ~/.Xauthority:/root/.Xauthority
      - ${STUDY_MACHINE_LEARNING_DIR}:/coursera-andrew-ng
    stdin_open: true
    tty: true

